In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset.head(133)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,46.0,80.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,160.000000,...,27.000000,8100.000000,3.200000,yes,no,no,poor,poor,yes,yes
129,46.0,110.000000,d,0.0,0.0,normal,normal,notpresent,notpresent,130.000000,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,no,yes
130,46.0,60.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,123.000000,...,50.000000,6300.000000,4.800000,no,no,no,yes,poor,no,no
131,46.0,60.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,102.000000,...,44.000000,11000.000000,5.400000,no,no,no,yes,poor,no,no
132,46.0,70.000000,b,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,43.000000,5700.000000,6.500000,no,no,no,yes,poor,no,no

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True, dtype=int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, cv = 5, verbose = 3, n_jobs=-1, scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [12]:
from sklearn.metrics import f1_score

# Get the predicted labels
y_pred = grid.predict(indep)

# Calculate the F1 score using the predicted labels and the true labels
f1_macro = f1_score(dep, y_pred, average='weighted')

# Print the F1 score and the best parameters
print("The f1_macro value for best parameter {}:".format(grid.best_params_), f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'auto', 'n_estimators': 100}: 0.47960178223336125

C:\Users\rohit\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [13]:
# Fitting the model using GridSearchCV
grid.fit(indep, dep)

# Getting the best model from grid search
classifier = grid.best_estimator_

# Predict on the test set
y_pred = classifier.predict(indep)

# Evaluate the predictions
from sklearn.metrics import confusion_matrix, classification_report

cm = confusion_matrix(dep, y_pred)
clf_report = classification_report(dep, y_pred)

print(clf_report)
print(cm)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       150
           1       1.00      1.00      1.00       249

    accuracy                           1.00       399
   macro avg       1.00      1.00      1.00       399
weighted avg       1.00      1.00      1.00       399

[[150   0]
 [  0 249]]

In [14]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 10}

In [15]:
import pandas as pd
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.114620,0.032598,0.023377,0.031956,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.937500,0.990099,0.970297,0.989899,1.000000,0.977559,0.022229,9
1,0.772030,0.052539,0.034624,0.030766,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.948454,1.000000,0.980392,0.989899,1.000000,0.983749,0.019095,2
2,0.054269,0.033547,0.024732,0.014619,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.903226,1.000000,0.980392,0.989899,1.000000,0.974703,0.036475,10
3,0.741019,0.039722,0.076530,0.015071,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.948454,0.990099,0.980392,0.989899,1.000000,0.981769,0.017775,6
4,0.107701,0.039447,0.018891,0.021183,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.903226,1.000000,0.980392,0.989899,0.989899,0.972683,0.035278,11
5,0.571191,0.045069,0.047705,0.021421,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.948454,1.000000,0.980392,0.989899,1.000000,0.983749,0.019095,2
6,0.166392,0.133011,0.013133,0.012271,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.937500,1.000000,0.990099,0.989899,1.000000,0.983500,0.023431,4
7,0.520561,0.017062,0.045099,0.023611,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.948454,0.990099,0.980392,0.989899,1.000000,0.981769,0.017775,6
8,0.034402,0.015256,0.017655,0.020393,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.800000,0.989899,0.980392,0.989899,1.000000,0.952038,0.076272,12
9,0.508378,0.057109,0.042224,0.029548,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.948454,0.990099,0.980392,0.989899,1.000000,0.981769,0.017775,6
10,0.058347,0.014814,0.014772,0.013109,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.969072,0.980000,0.989899,0.989899,1.000000,0.985774,0.010476,1
11,0.566571,0.018767,0.035244,0.022360,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.937500,1.000000,0.990099,0.989899,1.000000,0.983500,0.023431,4

In [18]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

1.0

In [19]:
import pandas as pd
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)

In [20]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.114620,0.032598,0.023377,0.031956,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.937500,0.990099,0.970297,0.989899,1.000000,0.977559,0.022229,9
1,0.772030,0.052539,0.034624,0.030766,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.948454,1.000000,0.980392,0.989899,1.000000,0.983749,0.019095,2
2,0.054269,0.033547,0.024732,0.014619,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.903226,1.000000,0.980392,0.989899,1.000000,0.974703,0.036475,10
3,0.741019,0.039722,0.076530,0.015071,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.948454,0.990099,0.980392,0.989899,1.000000,0.981769,0.017775,6
4,0.107701,0.039447,0.018891,0.021183,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.903226,1.000000,0.980392,0.989899,0.989899,0.972683,0.035278,11
5,0.571191,0.045069,0.047705,0.021421,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.948454,1.000000,0.980392,0.989899,1.000000,0.983749,0.019095,2
6,0.166392,0.133011,0.013133,0.012271,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.937500,1.000000,0.990099,0.989899,1.000000,0.983500,0.023431,4
7,0.520561,0.017062,0.045099,0.023611,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.948454,0.990099,0.980392,0.989899,1.000000,0.981769,0.017775,6
8,0.034402,0.015256,0.017655,0.020393,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.800000,0.989899,0.980392,0.989899,1.000000,0.952038,0.076272,12
9,0.508378,0.057109,0.042224,0.029548,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.948454,0.990099,0.980392,0.989899,1.000000,0.981769,0.017775,6
10,0.058347,0.014814,0.014772,0.013109,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.969072,0.980000,0.989899,0.989899,1.000000,0.985774,0.010476,1
11,0.566571,0.018767,0.035244,0.022360,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.937500,1.000000,0.990099,0.989899,1.000000,0.983500,0.023431,4