In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True, dtype=int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [7]:
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import numpy as np

# Initialize the Complement Naive Bayes model
cnb = ComplementNB()

# Define the parameter grid
param_grid = {
    'alpha': [0.1, 0.5, 1.0, 2.0, 5.0], # Smoothing parameter
    'norm': [True, False]               # Whether to normalize data
}

grid = GridSearchCV(estimator=cnb, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

grid.fit(indep, dep)

y_pred = grid.predict(indep)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(dep, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(dep, y_pred)
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.79      0.97      0.87       150
           1       0.98      0.84      0.91       249

    accuracy                           0.89       399
   macro avg       0.88      0.91      0.89       399
weighted avg       0.91      0.89      0.89       399

[[145   5]
 [ 39 210]]

In [8]:
from sklearn.metrics import f1_score

# Get the predicted labels
y_pred = grid.predict(indep)

# Calculate the F1 score using the predicted labels and the true labels
f1_macro = f1_score(dep, y_pred, average='weighted')

# Print the F1 score and the best parameters
print("The f1_macro value for best parameter {}:".format(grid.best_params_), f1_macro)

The f1_macro value for best parameter {'alpha': 0.1, 'norm': False}: 0.8912968721618211

In [9]:
from sklearn.metrics import roc_auc_score
roc_auc_score(dep,grid.predict_proba(indep)[:,1])

0.9623025435073628

In [10]:
import pandas as pd
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_norm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.031632,0.023650,0.003005,0.001518,0.1,True,"{'alpha': 0.1, 'norm': True}",0.3750,0.3750,0.3750,0.375,0.379747,0.375949,0.001899,6
1,0.037341,0.027690,0.002511,0.002287,0.1,False,"{'alpha': 0.1, 'norm': False}",0.7000,0.9000,0.9375,0.925,0.936709,0.879842,0.090936,1
2,0.022004,0.030728,0.003501,0.000778,0.5,True,"{'alpha': 0.5, 'norm': True}",0.3750,0.3750,0.3750,0.375,0.379747,0.375949,0.001899,6
3,0.019421,0.029613,0.018110,0.025621,0.5,False,"{'alpha': 0.5, 'norm': False}",0.6750,0.8875,0.9125,0.925,0.924051,0.864810,0.095864,2
4,0.018967,0.026939,0.003896,0.001115,1.0,True,"{'alpha': 1.0, 'norm': True}",0.3750,0.3750,0.3750,0.375,0.379747,0.375949,0.001899,6
5,0.007859,0.005134,0.002904,0.002502,1.0,False,"{'alpha': 1.0, 'norm': False}",0.6625,0.8625,0.9000,0.900,0.924051,0.849810,0.095704,3
6,0.005625,0.001966,0.015256,0.019997,2.0,True,"{'alpha': 2.0, 'norm': True}",0.3750,0.3750,0.3750,0.375,0.379747,0.375949,0.001899,6
7,0.007621,0.001728,0.002194,0.001828,2.0,False,"{'alpha': 2.0, 'norm': False}",0.6500,0.8625,0.8875,0.900,0.911392,0.842278,0.097502,4
8,0.006518,0.000640,0.031213,0.034785,5.0,True,"{'alpha': 5.0, 'norm': True}",0.3750,0.3750,0.3750,0.375,0.379747,0.375949,0.001899,6
9,0.007612,0.001293,0.022861,0.038966,5.0,False,"{'alpha': 5.0, 'norm': False}",0.6250,0.8625,0.8625,0.900,0.898734,0.829747,0.103693,5